# Location: src/analysis/session.py
"""
Analysis session orchestrator.

This module defines the AnalysisSession class, which manages the analysis
phase of the framework. It maintains the base Pareto front, applies
enrichment and framing filters, and coordinates the generation and
management of Sets of Interest (SOIs) produced by analytical lenses.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
import io
import pandas as pd

from src.domain.core.collection import SolutionSetCollection, SolutionSet
from src.domain.core.paretofront import ParetoFront
from src.solving.core.problem import OptimizationProblem

from src.analysis.framing import (
    get_framing_dimensions,
    get_dimension_bounds,
    apply_framing_bounds,
)
from src.analysis.enrichment import (
    get_available_indicators,
    compute_enrichment_indicators,
)


@dataclass
class AnalysisSession:
    """
    Main orchestrator for the analysis phase.

    This class holds the base Pareto front, applies enrichment and
    framing (bounding) filters, and manages a collection of SOIs
    (Sets of Interest) generated by analytical lenses.

    Attributes:
        base_front: The original Pareto front to analyse.
        name: Human‑readable session name.
        model: Optional reference to the OptimizationModel (used for enrichment).
        soi_collection: Collection of generated SolutionSets (SOIs, clusters, etc.).
        active_soi_id: ID of the currently selected SOI.
        _df: Internal DataFrame representation of the current working data.
        _active_bounds: Currently applied framing bounds (dimension -> (min, max)).
        _enriched_indicators: List of enrichment indicators that have been computed.
    """
    base_front: ParetoFront
    name: str = "Analysis Session"
    model: Optional[Any] = None

    soi_collection: SolutionSetCollection = field(default_factory=SolutionSetCollection)
    active_soi_id: Optional[str] = None

    _df: pd.DataFrame = field(init=False, repr=False)
    _active_bounds: Dict[str, Tuple[float, float]] = field(default_factory=dict)
    _enriched_indicators: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Initialise the internal DataFrame and collection name."""
        if not self.soi_collection.name:
            self.soi_collection.name = f"SOIs - {self.name}"
        self._df = self.base_front.to_dataframe()

    @classmethod
    def from_csv(
        cls,
        filepath_or_buffer: Union[str, Path, io.StringIO],
        name: str = "CSV Analysis",
        **loader_kwargs
    ) -> "AnalysisSession":
        """
        Create an AnalysisSession by loading a Pareto front from a CSV file.

        Args:
            filepath_or_buffer: Path or buffer containing CSV data.
            name: Name for the session.
            **loader_kwargs: Additional arguments passed to ParetoFront.from_csv.

        Returns:
            A new AnalysisSession instance.
        """
        front = ParetoFront.from_csv(filepath_or_buffer, **loader_kwargs)
        return cls(base_front=front, name=name)

    @classmethod
    def from_problem_set(
        cls,
        problem: OptimizationProblem,
        set_id: str
    ) -> "AnalysisSession":
        """
        Create an AnalysisSession from a SolutionSet stored in an OptimizationProblem.

        Args:
            problem: The problem containing the collection.
            set_id: ID of the SolutionSet to use.

        Returns:
            A new AnalysisSession instance.
        """
        s_set = problem.solutions_collection[set_id]
        return cls(
            base_front=s_set.front,
            name=f"Analysis - {s_set.name}",
            model=problem.model
        )

    # -------------------------------------------------------------------
    # Enrichment and Framing
    # -------------------------------------------------------------------

    def get_available_indicators(self) -> Dict[str, Dict[str, Any]]:
        """
        Retrieve the list of enrichment indicators that can be computed
        on the current DataFrame.

        Returns:
            A dictionary mapping indicator names to their metadata.
        """
        return get_available_indicators(df=self._df, model=self.model)

    def enrich(self, indicators: List[str]) -> "AnalysisSession":
        """
        Compute enrichment indicators on the current DataFrame.

        Args:
            indicators: List of indicator names to compute.

        Returns:
            Self, for method chaining.
        """
        self._df = compute_enrichment_indicators(
            df=self._df,
            selected_indicators=indicators,
            model=self.model
        )
        self._enriched_indicators = list(set(self._enriched_indicators + indicators))
        return self

    def get_framing_dimensions(
        self,
        metrics: Optional[List[str]] = None,
        indicators: Optional[List[str]] = None
    ) -> List[str]:
        """
        Obtain the list of framing dimensions (numeric columns available for filtering).

        Args:
            metrics: Additional metric columns to include.
            indicators: Indicator columns to include (defaults to computed indicators).

        Returns:
            A list of dimension names.
        """
        return get_framing_dimensions(
            metrics=metrics,
            indicators=indicators or self._enriched_indicators,
            df=self._df
        )

    def get_dimension_bounds(self, dimensions: List[str]) -> Dict[str, Tuple[float, float]]:
        """
        Compute min/max bounds for the specified dimensions.

        Args:
            dimensions: List of column names.

        Returns:
            A dictionary mapping each dimension to its (min, max) bounds.
        """
        return get_dimension_bounds(df=self._df, dimensions=dimensions)

    def apply_framing(self, bounds: Dict[str, Tuple[float, float]]) -> ParetoFront:
        """
        Apply framing bounds to the current DataFrame and return a new ParetoFront.

        The bounds are stored in `_active_bounds` and applied to subsequent operations.

        Args:
            bounds: Dictionary mapping dimension names to (min, max) tuples.

        Returns:
            A new ParetoFront containing only solutions within the bounds.
        """
        framed_df = apply_framing_bounds(df=self._df, bounds=bounds)
        self._active_bounds.update(bounds)

        # Extract objective column names from the first solution (if any)
        obj_cols = []
        if len(self.base_front) > 0:
            obj_cols = list(self.base_front.solutions[0].objectives.keys())

        return ParetoFront.from_dataframe(df=framed_df, objective_cols=obj_cols)

    # -------------------------------------------------------------------
    # Lenses and SOI Selection
    # -------------------------------------------------------------------

    def apply_lens(
        self,
        lens: Union[Any, str],
        params: Optional[Dict[str, Any]] = None,
        use_framed_front: bool = True,
        **kwargs: Any
    ) -> SolutionSet:
        """
        Apply an analytical lens to the current front and register the resulting SOI.

        Args:
            lens: A lens instance or a string (name) to resolve from the registry.
            params: Parameters to pass to the lens.
            use_framed_front: If True, applies framing first; otherwise uses the base front.
            **kwargs: Additional arguments passed to the lens evaluation.

        Returns:
            The resulting SolutionSet (SOI).
        """
        params = params or {}
        front_to_eval = self.apply_framing(self._active_bounds) if (use_framed_front and self._active_bounds) else self.base_front

        if isinstance(lens, str):
            from src.analysis.lenses.lens_pipeline import evaluate_lens
            soi = evaluate_lens(front_to_eval, lens_name=lens, params=params, **kwargs)
        else:
            soi = lens.evaluate(front_to_eval, params=params, **kwargs)

        self.soi_collection.add_set(soi)
        self.active_soi_id = soi.id
        return soi

    def promote_candidate_to_soi(
        self,
        candidate_set: SolutionSet,
        custom_name: Optional[str] = None
    ) -> SolutionSet:
        """
        Promote a candidate set (e.g., a cluster) to an official SOI.

        Args:
            candidate_set: The SolutionSet to promote.
            custom_name: Optional new name for the set (if not provided, the existing name is kept).

        Returns:
            The promoted SolutionSet (now categorised as 'soi').
        """
        if custom_name:
            candidate_set.name = custom_name
        candidate_set.category = "soi"
        self.soi_collection.add_set(candidate_set)
        self.active_soi_id = candidate_set.id
        return candidate_set

    def select_soi(self, soi_id: str) -> SolutionSet:
        """
        Select an SOI by its ID and set it as active.

        Args:
            soi_id: The ID of the SOI to select.

        Returns:
            The selected SolutionSet.

        Raises:
            KeyError: If the SOI ID does not exist in the collection.
        """
        if soi_id not in self.soi_collection.sets:
            raise KeyError(f"SOI with ID '{soi_id}' does not exist in the collection.")
        self.active_soi_id = soi_id
        return self.soi_collection[soi_id]

    @property
    def selected_soi(self) -> Optional[SolutionSet]:
        """
        Return the currently active SOI (if any).

        Returns:
            The active SolutionSet, or None if none is selected.
        """
        if self.active_soi_id and self.active_soi_id in self.soi_collection.sets:
            return self.soi_collection[self.active_soi_id]
        return None

    @property
    def current_dataframe(self) -> pd.DataFrame:
        """
        Return the current working DataFrame (with framing applied, if any).

        Returns:
            The DataFrame after applying any active framing bounds.
        """
        if self._active_bounds:
            return apply_framing_bounds(self._df, self._active_bounds)
        return self._df