# Location: src/analysis/soi.py
"""
Set of Interest (SOI) data structure.

This module defines the SOI dataclass, which represents a curated subset
of solutions identified during the analysis phase. SOIs are typically
generated by analytical lenses (e.g., consensus, clustering, preference
ranking) and can be saved, loaded, and compared.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class SOI:
    """
    A Set of Interest (SOI) representing a curated collection of solutions.

    SOIs are typically produced by analytical lenses (e.g., consensus,
    diversity clustering, preference ranking) and store the IDs of the
    solutions they contain along with provenance metadata.

    Attributes:
        id: Unique identifier for the SOI.
        name: Human‑readable name.
        solution_ids: List of solution IDs belonging to this set.
        lens_name: Name of the lens that generated this SOI.
        method_name: Specific method or algorithm used within the lens (optional).
        group: Optional group label (e.g., cluster ID, match count group).
        params: Parameters used when generating the SOI.
    """
    id: str
    name: str
    solution_ids: List[Any]
    lens_name: str
    method_name: Optional[str] = None
    group: Optional[str] = None
    params: Dict[str, Any] = field(default_factory=dict)

    @property
    def size(self) -> int:
        """
        Return the number of solutions in this SOI.

        Returns:
            The size (length) of the solution_ids list.
        """
        return len(self.solution_ids)